version: '3'

services:

  python:
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    volumes:
      - ./src/:/root/src/
    tty: true
    working_dir: /root/src

  mysql:
    build:
     context: .
     dockerfile: ./docker/mysql/Dockerfile
